# Generated by Django 4.0.3 on 2022-03-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
